name = "Fun"
license = "MIT"
licenselink = "https://github.com/gerardag/fun/blob/master/LICENSE.md"
description = "Starter Hugo theme for developers."
homepage = "https://github.com/gerardag/fun/"
tags = ["clean", "simple", "minimalist", "starter"]
features = ["personal site"]
min_version = 0.52

[author]
  name = "gerardag"
  homepage = "https://gerard.fun"
